### ISSUE TITLE
Publishing to Maven Central?

### ISSUE THREAD

**Issue by cmgrote** [numaproj/numaflow-java#28]
Hi there,

I'm hoping to use the Numaflow Java SDK as part of some sample code I'm putting together, but have found the use of GitHub Packages (and its required PAT-based authentication to the repository) to be a bit of a burden for others to re-use the samples.

So I was curious if there are any plans to publish the package to Maven Central?

Thanks!

**Comment by yhl25** [comment]
Hi @cmgrote 
I was hoping GitHub would remove the PAT-based authentication for public packages  [issue](https://github.com/orgs/community/discussions/26634#discussioncomment-5287689). But I don't think there are going to do it anytime soon, so I think it's a good idea to publish the artifacts to Maven Central. I will work on this.

**Comment by cmgrote** [comment]
Agree, it would be great if they did! But seems to indeed be a long-standing open problem 😞 Will be awesome to have it in Maven Central directly!

While the initial setup isn't fully self-service like GH Packages, the turnaround from Sonaytype seems to be pretty quick these days (https://central.sonatype.org/publish/publish-guide/)

**Comment by yhl25** [comment]
@cmgrote I am working on introducing tags for conditional forwarding which requires major API changes in this sprint, we are almost done with the changes and we are planning to cut a release soon which will have stable interfaces and APIs, post that I will pick this up(most probably next sprint).

**Comment by cmgrote** [comment]
Awesome, thanks for the update!

> we are planning to cut a release soon which will have stable interfaces and APIs

I noticed that between 0.3.4 and 0.4.0 the `MapFunc` disappeared and now the interface is to write a class that extends `MapHandler`. I like this change, but took a bit of debugging on my end when the bump from 0.3.4 to 0.4.0 suddenly broken my code... Does the "stable interfaces and APIs" comment mean that any such breaking changes will soon become major version changes in the SDK? 🙏

(I totally get the volatility in these pre-v1.0 versions, and do the same myself — but for sure it will make dependency management more consistent and reliable for consumers like me once semver is adopted 😁)

**Comment by vigith** [comment]
https://issues.sonatype.org/browse/OSSRH-90763

**Comment by yhl25** [comment]
@cmgrote We have published artifacts to Maven [Central](https://central.sonatype.com/artifact/io.numaproj.numaflow/numaflow-java/0.4.6/overview). Upgrade to the latest stable version 0.4.6. Please go through the [examples](https://github.com/numaproj/numaflow-java/tree/main/examples/src/main/java/io/numaproj/numaflow/examples) since the latest release has breaking changes.
